# Generated by Django 4.2.9 on 2024-04-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_comissoes_btg"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comissoes_btg",
            old_name="info",
            new_name="nome",
        ),
        migrations.RemoveField(
            model_name="comissoes_btg",
            name="name",
        ),
        migrations.RemoveField(
            model_name="comissoes_btg",
            name="price",
        ),
        migrations.AddField(
            model_name="comissoes_btg",
            name="corretagem_fixa",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comissoes_btg",
            name="corretagem_percentual",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comissoes_btg",
            name="criterio",
            field=models.CharField(default="maximo", max_length=100),
        ),
        migrations.AddField(
            model_name="comissoes_btg",
            name="observacao",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="comissoes_btg",
            name="tipo",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
