# Generated by Django 4.2.9 on 2024-04-04 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_produtos_remove_comissoes_btg_tipo_comissoes_aai_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
